from flask import Flask, render_template, url_for, redirect, request


app = Flask(__name__)


users ={}


def get_consoles():
    consoles = [
        {"id": 1, "name": "PlayStation 5", "description": "Play Station 5 | 825gb", "price": 550, "image": "static/images/consoles/image1.jpg", 'date' : '12 nov. 2020', 'genre': 'Console', 'platform' : 'PLay Station 5', 'main' : 'PlayStation 5: the next generation of gamingPS5 is Sonys next-generation gaming console, released in 2020. It features powerful hardware that delivers stunning graphics, realistic sound and immersive gameplay.PS5 offers players:* An extensive game library, including exclusive titles such as Horizon Forbidden West, Gran Turismo 7 and Ratchet & Clank: Rift Apart.* The ability to play games in 4K and 8K resolution while enjoying realistic graphics and ray tracing effects.* Immerse yourself in game worlds with Tempest 3D sound, which creates a surround sound experience.* Use the new DualSense controller with adaptive triggers, haptic feedback and a built-in microphone for a more realistic gaming experience.* Load games quickly thanks to SSD storage.* Play PS4 games thanks to backwards compatibility.* Connect PlayStation VR and play virtual reality games.* Use PlayStation Plus subscription, which gives you access to online multiplayer, free games every month and exclusive discounts.* Buy games, DLC, movies, TV series and more from the PlayStation Store.The PS5 is a powerful and feature-rich console that will be a great choice for gamers who want to get the most out of their games.Important to note:* PS5 is available in two versions: with and without a Blu-ray optical drive.* The PS5 can be mounted either vertically or horizontally.* PS5 requires a TV with HDMI 2.0 support.* PS5 is an expensive console, so you should carefully weigh the pros and cons before buying it.'},
        {"id": 2,"name": "PlayStation 4 Pro", "description": "PlayStation 4 Pro | 1TB", "price": 500, "image": "static/images/consoles/image2.webp", 'date' : '10 nov. 2016', 'genre': 'Console', 'platform' : "PlayStation 4 Pro", "main" : "PlayStation 4 Pro is a gaming console that deserves to be admired, offering you a unique gaming experience.With 4K resolution, you can enjoy games with stunning detail and realism that seemed unattainable before.HDR technology gives game scenes vivid and rich colors, giving them depth and realism. The console's processor and graphics chip work in harmony to deliver smooth and seamless gameplay without lags or interruptions.The innovative design of PlayStation 4 Pro makes it not only a powerful gaming device, but also a stylish accessory for your interior. With the ability to stream 4K video and watch Blu-ray discs, the console will become the center of entertainment in your home.Compatibility with a wide range of games and applications makes PlayStation 4 Pro the perfect choice for all types of players.With PlayStation Network, you can play online games, chat with friends and share your experiences without any restrictions.The intuitive interface makes using the console easy and convenient even for beginners.With support for PlayStation VR virtual reality, PlayStation 4 Pro opens the door to a world of exciting and exciting games and experiences. The variety of exclusive games available only on PlayStation makes this console unique and attractive to all fans of the gaming industry.The compact size of the PlayStation 4 Pro allows you to install it anywhere in your home, even if space is limited.With multiple USB and HDMI ports, you can easily connect various devices and accessories to the console.The DualShock 4 controller provides comfortable control and responds to your every movement, adding depth to your interaction with games.PlayStation 4 Pro is not just a console, it is a platform that unites"},
        {"id": 3,"name": "Xbox Series X", "description": "XBox Series X | 1TB", "price": 400, "image": "static/images/consoles/image3.jpg", 'date' : '10 nov. 2020', 'genre': 'Console', 'platform' :"Xbox Series X", "main" : "Welcome to a world of incredible gaming experiences with Xbox Series X, the next generation of gaming console from Microsoft. Xbox Series X is a powerful console capable of offering players incredible 4K resolution and the ability to enjoy games in stunning quality. Thanks to HDR technology, every game on Xbox Series X comes alive with vibrant and rich colors, creating stunning visuals. The Xbox Series X processor delivers high performance, allowing games to load faster and run smoother than ever before. With fast loading games and instant access to content, you can quickly immerse yourself in the gaming world without unnecessary lag. The compact and stylish design of Xbox Series X will fit perfectly into your interior and become the entertainment center of your home. Compatibility with a multitude of games and apps makes the Xbox Series X a versatile device for different types of players. With Xbox Game Pass, you'll have access to a huge library of games, including new releases and classic hits, for a small monthly fee. The Xbox Series X controller provides easy-to-use controls and precise motion tracking that adds depth to your interaction with games. With Xbox Series X, you can enjoy gameplay at resolutions up to 120 frames per second for smooth and realistic gameplay. Innovative Xbox Velocity Architecture and DirectStorage technologies ensure that games load quickly and run continuously without lag. With Xbox Series X, you can also stream videos in 4K resolution and enjoy movies and shows in stunning quality. Virtual Reality support lets you immerse yourself in immersive virtual worlds and games. The large internal memory capacity allows you to store lots of games and multimedia content on your console. Xbox Series X maximizes compatibility with previous generation Xbox games, so you can enjoy classic hits in a new way. With Xbox Live, you can play online games with friends and chat with them in real time. A series of exclusive games from Microsoft makes Xbox Series X an attractive choice for fans of gaming and exclusive content. Integration with Xbox Cloud Gaming allows you to play your favorite games on any device, wherever you are. Xbox Series X is more than just a gaming console, its a platform that opens up a world of endless gaming and entertainment possibilities."},
        {"id": 4,"name": "Xbox Series S", "description": "Xbox Series S | White | 512GB", "price": 270, "image": "static/images/consoles/image4.webp", 'date' : '10 nov. 2020', 'genre': 'Console', 'platform' :"Xbox Series S", "main" : "Welcome to a world of immersive gaming experiences with Xbox Series S, the compact and powerful gaming console from Microsoft. Xbox Series S offers stunning resolution for gaming up to 1440p, delivering stunning graphics and detail. With support for HDR technology, every gaming moment comes alive with vibrant colors and deep contrast. The powerful Xbox Series S processor delivers high performance, allowing games to load quickly and without lag. Compact Xbox Series design With Xbox Game Pass, you get access to a huge variety of games for a flat monthly fee. The Xbox Series S controller provides comfortable control and precise motion tracking for the ultimate gaming experience. With Xbox Series S, you can enjoy gameplay at resolutions up to 120 frames per second for a smooth and realistic gaming experience. With innovative Xbox Velocity Architecture and DirectStorage technologies, games load quickly and run without lag. Support for streaming services lets you enjoy watching movies and TV shows in stunning quality right from your console. A built-in library of games and apps makes the Xbox Series S a complete multimedia center for your home. With compatibility with previous generation Xbox games, you can enjoy classic hits in a new way. Xbox Series S is the perfect solution for those looking for a powerful and compact gaming console at an affordable price."},
        {"id": 5,"name": "Nintendo Switch Oled", "description": "Nintendo Switch Oled | White | 64GB", "price": 500, "image": "static/images/consoles/image5.avif", 'date' : '8 okt. 2021', 'genre': 'Console', 'platform' : "Nintendo Switch Oled", "main" : "Nintendo Switch OLED is an improved version of the popular gaming console, offering a bright and crisp OLED screen with deeper colors and better contrast. With this screen, the gaming experience becomes even more immersive and realistic. The console provides not only a portable gaming experience, but also the ability to connect to your TV for docked gaming. The stylish design and user-friendly controllers make the Nintendo Switch OLED appealing to gamers of all ages. With a wide selection of games from Nintendo and other publishers, you'll always have something new to explore. Nintendo Switch OLED supports both single-player and multiplayer modes, allowing you to play together with friends and family. With the Joy-Con detachable controllers feature, you can play your favorite games anywhere and anytime. The console's large screen and high-definition visuals make the gaming experience even more fun and emotional. Nintendo Switch OLED supports internet connectivity, allowing you to download updates and additional content for your games. Its compact size and light weight make it easy to take with you on the road or when traveling. The ability to use special cartridges and digital downloads makes Nintendo Switch OLED a convenient and versatile gaming device. The Nintendo eShop system offers a wide selection of games and additional content for your enjoyment. The innovative concept of the Nintendo Switch OLED console makes it a unique gaming device that can be your faithful companion on any gaming adventure."},
        {"id": 6,"name": "PlayStation 5 Slim DE", "description": "PS 5 Slim | 1Tb", "price": 570, "image": "static/images/consoles/image6.webp", 'date' : '28 feb. 2024', 'genre': 'Console', 'platform' : 'PlayStation 5 Slim DE', "main" : "PlayStation5 Console: The PS5 console opens up new gaming possibilities you never knew were possible. Experience ultra-fast loading times thanks to the ultra-fast SSD, a more immersive gaming experience with haptic feedback, adaptive triggers and 3D sound. Slim Design With PS5, gamers get powerful gaming technology packed into a sleek and compact console body. 1TB Storage Keep your favorite games ready and waiting to launch and play thanks to the built-in 1TB SSD storage.3 2 RequiresPlayStationNetwork account. Full terms and conditions apply - playstation.com/Terms of PSN.Ultrafast SSD Maximize your gaming sessions with near-instant loading of installed PS5 games. Integrated I/O Special integration of PS5 console systems allows creators to get data from the SSD so fast they can develop games like never before.Ray Tracing Immerse yourself in worlds with a new level of realism as light rays are individually modeled to create realistic shadows and reflections in compatible PS5 games. Gaming on 4K TVs Play your favorite PS5 games on a stunning 4K TV. Up to 120 frames per second at 120Hz Enjoy smooth and fluid gameplay with high frame rates of up to 120 frames per second in compatible games that support 120Hz on 4K displays."},
        {"id": 7,"name": "Xbox Series S", "description": "Xbox Series S | White | 512GB", "price": 270, "image": "static/images/consoles/image4.webp", 'date' : '10 nov. 2020', 'genre': 'Console', 'platform' :"Xbox Series S", "main" : "Welcome to a world of immersive gaming experiences with Xbox Series S, the compact and powerful gaming console from Microsoft. Xbox Series S offers stunning resolution for gaming up to 1440p, delivering stunning graphics and detail. With support for HDR technology, every gaming moment comes alive with vibrant colors and deep contrast. The powerful Xbox Series S processor delivers high performance, allowing games to load quickly and without lag. Compact Xbox Series design With Xbox Game Pass, you get access to a huge variety of games for a flat monthly fee. The Xbox Series S controller provides comfortable control and precise motion tracking for the ultimate gaming experience. With Xbox Series S, you can enjoy gameplay at resolutions up to 120 frames per second for a smooth and realistic gaming experience. With innovative Xbox Velocity Architecture and DirectStorage technologies, games load quickly and run without lag. Support for streaming services lets you enjoy watching movies and TV shows in stunning quality right from your console. A built-in library of games and apps makes the Xbox Series S a complete multimedia center for your home. With compatibility with previous generation Xbox games, you can enjoy classic hits in a new way. Xbox Series S is the perfect solution for those looking for a powerful and compact gaming console at an affordable price."},
        {"id": 8,"name": "Asus ROG Ally Extreme", "description": "Asus ROG Ally Extreme| 512gb | White", "price": 846, "image": "static/images/consoles/image8.avif", 'date' : '13 jun. 2023', 'genre': 'Console', 'platform' : "Asus ROG Ally Extreme", "main" : "It's not a game console, but a full-fledged Windows PC, powerful enough to replace desktop PCs with a docking station. As for the gamepad, Asus added two keys to layer the console even during the game. The joysticks are comfortable, but it takes time to get used to. The screen is bright and pleasant, and the eyes do not strain. Powerful speakers that block the sound from the cooling system. The battery capacity is not enough for a long game, the same with the hard disk, it's small :), setting up Windows and updating the system will take a lot of time, and keeping a password on such a screen is a quest. Wi-Fi supports 802.11ax, but does not support WPA3 encryption, so there may be problems with connecting to wifi."},
        {"id": 9,"name": "Nintendo Switch Lite", "description": "Nintendo Switch Lite | 32gb | Gray", "price": 290, "image": "static/images/consoles/image10.jpg", 'date' : '10 jul. 2019', 'genre': 'Console', 'platform' : "Nintendo Switch Lite", "main" : "Конечно, вот такое описание:Nintendo Switch Lite - это компактная и портативная версия популярной игровой консоли, предназначенная для игры в движении. Благодаря своим небольшим размерам и легкому весу, Nintendo Switch Lite идеально подходит для игр в пути или в дороге. Консоль оснащена ярким 5,5-дюймовым экраном с разрешением 720p, который обеспечивает четкое и качественное изображение. Nintendo Switch Lite доступен в нескольких стильных цветах, что позволяет выбрать оптимальный вариант для вашего стиля. Как и оригинальная версия Nintendo Switch, Nintendo Switch Lite поддерживает богатую библиотеку игр, включая эксклюзивные заголовки от Nintendo. Благодаря встроенной памяти и поддержке microSD-карт вы сможете хранить большое количество игр и контента на консоли. Консоль также поддерживает возможность подключения к телевизору с помощью док-станции (продаётся отдельно) для игры на большом экране. Nintendo Switch Lite обеспечивает длительное время автономной работы благодаря энергоэффективной батарее, что позволяет наслаждаться играми дольше. Удобный и эргономичный дизайн консоли обеспечивает комфортное управление и игровой опыт. Благодаря возможности игры с друзьями через беспроводное подключение, вы сможете наслаждаться многопользовательскими играми где угодно. Nintendo Switch Lite - это идеальный выбор для тех, кто ценит портативность, качество и разнообразие игрового опыта."},
        {"id": 10,"name": "Steam Deck", "description": "Steam Deck | Oled | 1TB", "price": 1170, "image": "static/images/consoles/image11.webp", 'date' : '25 feb. 2022', 'genre': 'Console', 'platform' : "Steam Deck", "main" : "Конечно! Вот описание Steam Deck:Steam Deck - это инновационная портативная игровая консоль от Valve, которая позволяет вам играть в ваши любимые игры Steam везде, где вы захотите. Снабженная процессором AMD, Steam Deck обеспечивает высокую производительность для запуска самых требовательных игр. Ее 7-дюймовый экран с разрешением 1280x800 и частотой обновления 60 Гц обеспечивает четкое и качественное изображение. Steam Deck имеет встроенный контроллер, а также возможность подключения внешних контроллеров через Bluetooth или USB-C. Благодаря операционной системе SteamOS 3.0 вы получаете доступ к вашей библиотеке Steam и каталогу игр Steam сразу после включения устройства. Steam Deck оснащен аккумулятором емкостью до 40 Втч, что обеспечивает длительное время игры вдали от розетки. Вы также можете подключить Steam Deck к монитору или телевизору через порт USB-C и использовать его как домашнюю игровую консоль. Steam Deck предлагает различные конфигурации хранения, включая 64, 256 и 512 ГБ встроенной памяти, а также слот для карт памяти microSD для дополнительного хранения. Эта портативная консоль поддерживает функции воспроизведения в облаке и стриминга игр с вашего ПК через Wi-Fi. Благодаря встроенной поддержке Bluetooth вы можете подключить беспроводные наушники или аудиосистему к Steam Deck для удобного игрового звука. Steam Deck - это революционное устройство, которое позволяет вам взять ваши любимые игры Steam в путешествие и играть в них где угодно."},
    ]
    return consoles


def get_phones():
    phones = [
        {"id": 11, "name": "iPhone 15 Pro Max", "description": "iPhone 15 Pro Max | 256gb | Natural Titanium", "price": 1500, "image": "static/images/phones/image9.webp", 'date' : '12 sep. 2023', 'genre': 'Phones', 'platform' : "iPhone 15 | Pro Max", "main" : "1. Appearance: Stylish brushed aluminum case, pleasant to the touch. The gradient glass back panel shimmers in the light. The rounded edges fit comfortably in the hand and the light weight makes it easy to use with one hand. On the front side, there is a frameless screen and a fingerprint scanner underneath it. On the back side, there is a triple camera with flash, as well as the manufacturer's logo.2- The screen:A bright and saturated AMOLED screen with a diagonal of 6.5 inches provides comfortable viewing of videos and photos, as well as reading text. Full HD+ resolution (2340x1080 pixels) guarantees high image detail. The 90Hz refresh rate makes the picture smoother.3. Camera:The phone's main camera has a 48-megapixel sensor and allows you to take high-quality photos even in low light. The ultra wide-angle lens can capture panoramic landscapes, while the telephoto lens offers 2x optical zoom. The 32-megapixel front camera lets you take selfies and video chat.4. Performance:The powerful Snapdragon 778G 8-core processor and 8GB of RAM keep the phone running smoothly in even the most demanding applications. 128GB of internal memory is expandable via microSD card. 5. Battery:A capacious 5000 mAh battery gives the phone a long battery life. With moderate usage, it can last up to 2 days without recharging."},
        {"id": 12, "name": "Xiaomi 14", "description": "Xiaomi 14 | 512gb | Black", "price": 1050, "image": "static/images/phones/image12.avif", 'date' : '25 feb. 2024', 'genre': 'Phones', 'platform' : "Xiaomi | 14 ", "main" : "The stylish and ergonomic premium aluminum and glass body fits comfortably in your hand, and the compact size makes it easy to operate the phone with one hand. Available in multiple colors to match your style.The 6.36-inch AMOLED display with FHD+ (1200x2670) resolution delivers stunning visual clarity. The 120Hz refresh rate ensures a smooth picture whether you're gaming, watching videos or surfing the web. Enjoy vivid colors and deep blacks thanks to HDR10+ technology. The next-generation Qualcomm Snapdragon 8 Gen 3 processor delivers top-notch performance for all your tasks. 8/12/16GB of RAM ensures smooth multitasking. 256/512GB of internal memory lets you store all your photos, videos, apps and games.The 50 MP main camera with Optical Image Stabilization (OIS) lets you take professional-quality photos and videos. The 12 MP ultra-wide-angle camera is ideal for panoramic shots, while the 8 MP telephoto lens with 3x optical zoom provides excellent detail when capturing distant subjects. A capacious 4610 mAh battery provides up to 2 days of battery life without recharging. 90W fast charging support allows you to charge your phone to 100% in just 30 minutes."},
        {"id": 13, "name": "Poco X6 Pro", "description": "Poco X6 Pro | 512gb | Black", "price": 420, "image": "static/images/phones/image13.avif", 'date' : '24 jan. 2024', 'genre': 'Phones', 'platform' : "Poco | X6 Pro", "main" : "Poco X6 Pro: A powerful and affordable gamer in your pocketGaming to the max: The Poco X6 Pro is powered by the latest flagship MediaTek Dimensity 8300 Ultra processor, which blows away any game at high settings. With 8/12GB of RAM, everything runs smoothly and lag-free, and 256/512GB of internal storage is enough for a huge collection of games and apps.Beat the Display: The 6.67-inch Flow AMOLED screen with 1.5K CrystalRes resolution and 120Hz refresh rate delivers an incredible picture. Enjoy vivid rich colors, deep blacks and ultra-smooth animations that are perfect for gaming and watching movies.Triple buzz: The 64MP main camera takes clear pictures even in low light. The 8MP ultra-wide-angle camera captures more space, and the 2MP macro camera will let you see the smallest details. The 16MP front camera provides great selfies and video calls.Uninterrupted action: A capacious 5000mAh battery lets you play games, watch movies, or just use the phone for hours without charging. And 67W fast charging instantly replenishes power so you don't fall off your game.More than a phone: The Poco X6 Pro is more than just a gaming monster. It supports 5G networks for super-fast internet, with Wi-Fi 6, Bluetooth 5.3 and NFC for contactless payments."},
        {"id": 14, "name": "Samsung Galaxy Fold5", "description": "Samsung Galaxy Fold5 | 512gb | Black", "price": 2000, "image": "static/images/phones/image14.avif", 'date' : '26 jul. 2023', 'genre': 'Phones', 'platform' : "Samsung Galaxy | Fold5", "main" : "1. Innovative Foldable Display:Galaxy Fold5 features a stunning 7.6-inch Dynamic AMOLED 2X display that folds out to turn your phone into a tablet. Enjoy movies, games and multitasking on a big, bright screen with QXGA+ (3840x2160) resolution.2. Compact and stylish: When folded, Fold5 fits comfortably in your pocket with its 6.2-inch external display. The stylish premium glass and metal body looks modern and expensive.3. Powerful Performance:The next-generation Qualcomm Snapdragon 8 Gen 2 processor delivers lightning-fast performance for all applications and games. 12GB of RAM ensures smooth multitasking, and 256GB, 512GB or 1TB of internal storage is enough to store all your files.4. Professional Camera:The 50MP main camera with Optical Image Stabilization (OIS) allows you to capture studio-quality photos. Additional cameras - a 12MP ultra-wide-angle camera and a 12MP telephoto lens with 3x optical zoom - expand your creative possibilities. The 10MP + 4MP front camera under the display is perfect for selfies and video calls.5. Long-lasting performance: A capacious 4400mAh battery provides a full day of use without recharging. The 45W fast charging support allows you to replenish power quickly."},
        {"id": 15, "name": "OPPO Reno10 Pro", "description": "OPPO Reno10 Pro | 256gb | Silvery Grey", "price": 570, "image": "static/images/phones/image15.avif", 'date' : '7 jul. 2023', 'genre': 'Phones', 'platform' : "OPPO | Reno10 Pro", "main" : "1. Premium design: OPPO Reno10 Pro looks as impressive as it performs. The sleek body made of glossy plastic or frosted glass (depending on the version) fits comfortably in your hand, while the slim profile and light weight make it ideal for everyday use. Available in several stylish colors to enhance your personality.2. Bright and clear display: The 6.5-inch AMOLED screen with FHD+ resolution (2400x1080 pixels) delivers stunning visuals. The high refresh rate of 120Hz ensures a smooth picture whether you're gaming, watching videos or surfing the web. Enjoy rich colors and deep blacks with HDR10+ technology.3. Powerful next-generation processor: Qualcomm Snapdragon 7 Gen 2 keeps your phone running fast and power-efficient. Perform everything from everyday calls and social networking to demanding games and photo processing without lags or freezes.4. Triple camera for every shot: The 50MP main camera with Optical Image Stabilization (OIS) lets you take professional-quality photos in any light. The 8MP ultra-wide-angle camera captures more space in your panoramic photos, and the 2MP macro camera will capture the smallest details.5. Front camera for vivid selfies: the 32MP front camera delivers great selfies and video calls. Take vivid and detailed self-portraits and video calls with your loved ones with high quality images.6. Long battery life: The powerful 4800mAh battery will keep you active all day long. The 65W fast charging feature provides a quick boost of power to keep you connected."},
        {"id": 16, "name": "Samsung Galaxy S24 Ultra", "description": "Samsung Galaxy S24 Ultra | 512gb | Titanium Gray", "price": 1600, "image": "static/images/phones/image16.avif", 'date' : '17 nov. 2024', 'genre': 'Phones', 'platform' : "Samsung Galaxy | S24 Ultra", "main" : "1. Blazing-Fast Performance:The Galaxy S24 Ultra boasts the latest Qualcomm Snapdragon 8 Gen 4 processor, delivering unparalleled speed and efficiency. Whether you're multitasking, gaming, or editing 8K video, the S24 Ultra handles it all with ease. Choose from 12GB or a monstrous 16GB of RAM for seamless multitasking and future-proofing. 2. Stunning, Immersive Display:The 6.8-inch Dynamic AMOLED 2X display on the S24 Ultra is a feast for the eyes. With a QHD+ (3200 x 1440) resolution and a smooth 120Hz refresh rate, everything from games to movies comes alive with incredible detail and fluidity. HDR10+ certification ensures vibrant colors and deep blacks for a truly cinematic experience. 3. Pro-Grade Camera System:Capture stunning photos and videos in any lighting condition with the S24 Ultra's versatile quad-camera system. The 108-megapixel main sensor with OIS (Optical Image Stabilization) delivers exceptional clarity, while the 12-megapixel ultra-wide sensor expands your perspective. A dedicated 10-megapixel telephoto lens with 10x optical zoom brings distant subjects closer, and a 4-megapixel depth sensor creates stunning portrait shots. 4. S Pen Magic (Optional):Unleash your creativity with the S Pen (sold separately). Take detailed notes, create stunning artwork, or effortlessly control your phone with unmatched precision. The improved latency makes the S Pen feel natural and responsive, just like pen on paper. 5. All-Day Battery Life:The S24 Ultra is equipped with a massive 5500mAh battery that can easily power you through a full day of use. With support for 45W fast charging, you can quickly get back up and running when you need it most."},
        {"id": 17, "name": "OnePlus 9 Pro ", "description": "OnePlus 9 Pro | 128gb | Morning Mist", "price": 700, "image": "static/images/phones/image17.avif", 'date' : '23 mar. 2021', 'genre': 'Phones', 'platform' : "OnePlus | 9 Pro", "main" : "The OnePlus 9 Pro delivers high-end features at a competitive price, making it a compelling choice for those seeking a powerful and stylish smartphone. Here's a breakdown of its key features:1. Breathtaking Display: Immerse yourself in a vibrant world with the 6.7-inch Fluid AMOLED display. The 120Hz refresh rate ensures smooth visuals for gaming, scrolling, and video playback. Enjoy crisp visuals with a QHD+ (3216 x 1440) resolution and HDR10+ support for vivid colors and deep blacks.2. Flagship Performance: Power through demanding tasks with the lightning-fast Qualcomm Snapdragon 888 processor. Whether you're multitasking, running games, or editing videos, the 9 Pro handles it all with ease. Choose from 8GB or 12GB of RAM for seamless performance and future-proofing.3. Capture Stunning Moments: The quad-camera system on the back lets you capture professional-grade photos and videos. The 48MP main sensor with OIS (Optical Image Stabilization) delivers incredible detail, while the 50MP ultrawide sensor expands your perspective for capturing grand landscapes. An 8MP telephoto lens with 3x optical zoom brings distant subjects closer, and a 2MP monochrome sensor adds depth information for stunning portrait shots.4. Hasselblad Camera Experience: OnePlus has partnered with the legendary camera maker Hasselblad to bring you a superior camera experience. The OnePlus 9 Pro benefits from Hasselblad's expertise in color calibration and natural color reproduction, resulting in more realistic and lifelike photos.5. Warp Charge 65W: Never get caught with a dead battery again. The OnePlus 9 Pro supports Warp Charge 65W, which can juice up your phone from 0 to 100% in just 29 minutes. This ensures you're always ready to capture that perfect moment or stay connected throughout the day."},
        {"id": 18, "name": "vivo V23e ", "description": "vivo V23e | 128gb | Moonlight Shadow", "price": 250, "image": "static/images/phones/image18.avif", 'date' : '1 dec. 2021', 'genre': 'Phones', 'platform' : "vivo | V23e", "main": "The vivo V23e is a mid-range smartphone that offers a stylish design, decent performance, and a capable camera system, all at an affordable price. Here's a closer look at its key features:1. Striking Design:Turn heads with the vivo V23e's sleek and slim design. The phone is crafted from either plastic or glass (depending on the version) and comes in two captivating colors: Moonlight Shadow and Water Glimmer. The phone's lightweight and comfortable to hold, making it perfect for one-handed use.2. Vibrant Display:Enjoy immersive visuals on the 6.44-inch AMOLED display. The FHD+ (1080 x 2400) resolution offers sharp visuals, while the 60Hz refresh rate ensures smooth navigation and video playback.3. Capable Performance:The MediaTek Helio G96 processor delivers reliable performance for everyday tasks, light gaming, and social media use. Paired with 8GB of RAM, you can multitask between apps without experiencing lag.4. Capture Lasting Memories:The rear camera system boasts a 64MP main sensor that captures clear photos in daylight conditions. An 8MP wide-angle sensor helps you capture expansive landscapes, while a 2MP macro sensor allows you to take close-up shots with intricate details. The 50MP front camera with autofocus ensures you capture stunning selfies and video calls.5. Long-Lasting Battery: The 4050mAh battery provides enough juice to get you through a full day of moderate use. While it doesn't support the fastest charging speeds, the included 44W charger can provide a decent power boost when needed."}
    ]
    return phones



def get_ps_games():
    ps_games = [
        {"id": 19,"name": "PS5 Marvel's Spider-Man 2", "description": "PS - 5 | Spider Man - 3", "price": 70, "image": "static/images/games/image19.avif", 'date' : '20 oct. 2023', 'genre': 'Games', 'platform' : "PLay Station 5", "main" : "Both Spider-Man's Peter Parker and Miles Morales are in action! Swing on webs, crawl up steep walls, soar high into the air and try out new web wings. You will experience exciting adventures of each of the characters, get new, unique abilities and take part in tough battles with villains of different colors to protect your native New York and all its inhabitants from serious danger. Innovative technologies of the latest game console will help you to immerse yourself in your favorite game. Enjoy the beauty of New York City in incredible graphics and detail and 4K resolution. The ultra-fast SSD drive will make loading and switching between characters lightning fast. The game controller's responsive vibration and innovative adaptive triggers will give you an even better sense of Peter's symbiote powers and Miles' impressive bioelectric abilities. And AudioTech's Tempest 3D technology will give you an impressive three-dimensional sound experience, allowing you to clearly distinguish each sound and feel its direction."},
        {"id": 20,"name": "PS5 EA SPORTS FC 24", "description": "PS - 5 | Fifa - 24",  "price": 80, "image": "static/images/games/image20.jpg", 'date' : '29 sep. 2023', 'genre': 'Games', 'platform' : "PLay Station 5", "main" : "EA SPORTS FC 24 is the new and most realistic sports soccer simulator. More than 19 thousand fully licensed players, as well as more than 700 soccer teams and more than 30 different leagues will be waiting for you. Thanks to new innovative technologies you will be able to enjoy incredible realism of every soccer match, where every player will behave like a real one.The new HyperMotionV* technology allowed to recreate the maximum amount of details during soccer competitions. The game uses a huge amount of data recorded from over 180 real matches in various leagues, both male and female, to make the players' movements on the game screen as realistic as possible. PlayStyles, based on data from Opta and other sources, will recreate all the characteristic features and traits of each participant in a soccer match on the field, so that all of them will be uniquely different from each other. And the revolutionary FrosBite graphics engine will provide superior graphics quality and incredible detail that will bring the atmosphere of each match to a whole new level.Multiple modes are available, and everything is done at the highest level of excellence"},
        {"id": 21,"name": "PS5 The Last Of Us Part II Remastered", "description": "PS - 5 | TLOU 2 R",  "price": 35, "image": "static/images/games/image21.avif", 'date' : '19 jan. 2024', 'genre': 'Games', 'platform' : "PLay Station 5", "main" : "Play the winner of over 300 Game of the Year awards, remastered for the PlayStation®5 console. Relive or play for the first time Ellie and Abby’s story, now with graphical enhancements, new gameplay modes like the roguelike survival experience No Return, full DualSense® wireless controller integration, and more.Five years after their dangerous journey across the post-pandemic United States, Ellie and Joel have settled down in Jackson, Wyoming. Living amongst a thriving community of survivors has allowed them peace and stability, despite the constant threat of the infected and other, more desperate survivors. When a violent event disrupts that peace, Ellie embarks on a relentless journey to carry out justice and find closure."}
    ]

    return ps_games

def get_x_games():
    x_games = [
        {"id": 22, "name": "NBA 2K24", "description": "Xbox NBA 2K24 [X One | X Series X]", "price": 65, "image": "static/images/games/image22.avif", 'date' : '7 sep. 2023', 'genre': 'Games', 'platform' : "X Box Series X | X Box One", "main" : "Grab your squad and experience the past, present, and future of hoops culture in NBA 2K24. Enjoy loads of pure, unadulterated action and limitless personalized MyPLAYER options in MyCAREER. Collect an impressive array of legends and build your perfect lineup in MyTEAM. Feel more responsive gameplay and polished visuals while playing with your favorite NBA and WNBA teams in PLAY NOW."},
        {"id": 23, "name": "Xbox LEGO 2К Drive", "description": "Xbox NBA 2K24 [X One | X Series X]", "price": 65, "image": "static/images/games/image23.avif", 'date' : '19 may. 2023', 'genre': 'Games', 'platform' : "X Box Series X | X Box One", "main" : "Take part in the biggest racing events taking place in the LEGO world. You'll find yourself in Brickland, a large open world where you'll have the opportunity to move freely and take part in a wide variety of competitions. Races take place in various locations - classic race tracks, off-road, and even open water. And your vehicle will be a special transformer car, which you can improve brick by brick to earn even more rewards in races at incredible speeds. The story mode will tell you a fascinating story in which you will start your journey as a racer, being the most ordinary beginner. Later on you can earn more and more victories and cups to fight on equal terms with the most formidable opponent - Shadow Z. The standard single-player mode will allow you to start a random race, and Cup Series tournaments will give you the opportunity to compete against many other skillful racers for a valuable prize. In addition, you will have access to a variety of unique mini-games with unusual tasks. To achieve victory, you will not only have to get used to your car and develop excellent reactions, but also to master the art of drifting, as well as learn how to use various boosters and gas pedals during the race."},
        {"id": 24, "name": "Xbox S.T.A.L.K.E.R. 2", "description": "Xbox S.T.A.L.K.E.R. 2 Collector's Edition", "price": 155, "image": "static/images/games/image24.jpg", 'date' : '5 sep. 2024', 'genre': 'Games', 'platform' : "X Box Series X", "main" : "S.T.A.L.K.E.R. 2: Heart of Chernobyl is the continuation of the cult series of first-person shooters, taking place in an alternative version of the Chernobyl Exclusion Zone.Open a new chapter of the Zone's history, and as a lone stalker begin your own adventure in the vast and open world of the post-apocalypse. Fight for survival against formidable opponents and abnormal environment. Make your own way through anomalies and enemies to the legendary Heart of Chernobyl."}
    ]

    return x_games


all_products = get_consoles() + get_phones() + get_ps_games() + get_x_games()

@app.get("/")
def main():
    consoles = get_consoles()
    phones = get_phones()
    games = get_ps_games() + get_x_games()
    products = consoles + phones + games
    return render_template("index.html", products=products)


@app.get("/consoles")
def console():
    consoles = get_consoles()
    return render_template("consoles.html", products=consoles)


@app.get("/phones")
def phone():
    phones = get_phones()
    return render_template("phones.html", products=phones)


@app.get("/allgames")
def all_game():
    games = get_ps_games() + get_x_games()
    return render_template("games.html", products=games)

@app.get("/playstationgames")
def ps_game():
    games = get_ps_games()
    return render_template("ps_games.html", products=games)

@app.get("/xboxgames")
def x_game():
    games = get_x_games()
    return render_template("x_games.html", products=games)



@app.route('/product/<int:product_id>')
def product(product_id):
    selected_product = None
    for product in all_products:
        if product['id'] == product_id:
            selected_product = product
            break
    
    if selected_product is None:
        return "Product not found", 404
    
    return render_template('info.html', product=selected_product)




# A C C O U N T



@app.get("/auth")
def auth_get():
    return render_template('auth.html')

@app.post('/auth')
def auth_post():
    username = request.form['username']
    password = request.form['password']

    if username in users and users[username]['password'] == password:
        return render_template('welcome.html', username=username)
    
    else:
        return render_template('auth.html', message="Неправильний пароль або юзернейм")
    
@app.get('/register')
def register_get():
    return render_template('register.html')

@app.post('/register')
def register_post():
    username = request.form['username']
    password = request.form['password']

    if username in users:
        return render_template('register.html', message="Такий користувач вже існує!")
    
    else:
        users[username] = {"password" : password}
        print(users)
        return render_template('welcome.html', username=username)




if __name__ == '__main__':
    app.run(debug=True)
